version: "1"
rules:
  # Once main-au is validated and merged to main, uncomment line below and remove main-au rule
  # - base: main
  - base: main
    upstream: KelvinTegelaar:main
    mergeMethod: merge
  # Don't need dev noise 
  # mergeMethod is listed as none and we don't need to be tracking it.  
  #- base: dev
  #  upstream: KelvinTegelaar:dev
  #  mergeMethod: none
  # website: upstream doc site only, not needed for AU deployment
  #- base: website
  #  upstream: KelvinTegelaar:website
  #  mergeMethod: merge
